name: Custom Action Workflow
on: [push]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Custom Action
        uses: tonykachappilly/GitHub_Actions_Cert_Prep/custom_actions_js@main
        with:
          input_parameter: 'My World'
