name: Custom Action Workflow
on: [push]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Custom Action
        uses: ./  # Uses the local action repository
        with:
          input_parameter: 'test_input'
