name: Custom Action Workflow
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack
      - name: Run Custom Action
        uses: tonykachappilly/GitHub_Actions_Cert_Prep/custom_actions_js@main
        with:
          who-to-greet: 'My World'
