# This is a basic workflow to help you get started with Actions

name: ASP.NET Core Workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore src/GitHub_Actions_Cert_Prep.sln
      - name: Build
        run: dotnet build src/GitHub_Actions_Cert_Prep.sln --no-restore
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore src/GitHub_Actions_Cert_Prep.sln
      - name: Build
        run: dotnet build src/GitHub_Actions_Cert_Prep.sln --no-restore
      - name: Test
        run: dotnet test tests/GitHub_Actions_Cert_Prep.Tests/GitHub_Actions_Cert_Prep.Tests.csproj --no-build --list-tests
     
